### ISSUE TITLE
Undefined method `built_in_formatter'

### ISSUE THREAD

**Issue by davetoxa** [cupakromer/emoji-rspec#11]
Hello, I've got a strange error using emoji-rspec gem

```
➜  track2win git:(master) ✗ rspec --require emoji-rspec --format smiles
/Users/anton/.rvm/gems/ruby-2.1.2/gems/emoji-rspec-1.0.1/lib/emoji_test_love/rspec.rb:7:in `alias_method': undefined method `built_in_formatter' for class `RSpec::Core::Configuration' (NameError)
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/emoji-rspec-1.0.1/lib/emoji_test_love/rspec.rb:7:in `<class:Configuration>'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/emoji-rspec-1.0.1/lib/emoji_test_love/rspec.rb:5:in `<top (required)>'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/emoji-rspec-1.0.1/lib/emoji-rspec.rb:2:in `require'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/emoji-rspec-1.0.1/lib/emoji-rspec.rb:2:in `<top (required)>'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1024:in `require'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1024:in `block in requires='
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1024:in `each'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration.rb:1024:in `requires='
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration_options.rb:101:in `block in process_options_into'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration_options.rb:100:in `each'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration_options.rb:100:in `process_options_into'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/configuration_options.rb:22:in `configure'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:96:in `setup'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:85:in `run'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:70:in `run'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/lib/rspec/core/runner.rb:38:in `invoke'
    from /Users/anton/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.0.3/exe/rspec:4:in `<top (required)>'
    from ./bin/rspec:16:in `load'
    from ./bin/rspec:16:in `<main>'
```

**Comment by carhartl** [comment]
Looks like you're trying to use the formatter with RSpec 3, unfortunately support for it is in progress.

**Comment by davetoxa** [comment]
@carhartl yes, i've got rspec 3

**Comment by michaelmior** [comment]
I ran into the same issue. It would be nice to put include the fact that RSpec 3 isn't supported yet in the docs.

**Comment by chrishough** [comment]
bummer... I was hoping to use this too +1

**Comment by ghost** [comment]
I downgraded to `gem "rspec", "~> 2"` but I get the same error. What version of RSpec does this work with?

**Comment by chrishough** [comment]
Is this issue repaired? I noticed it was just closed?

**Comment by rubendinho** [comment]
+1 on adding a note about RSpec 3 incompatibility.
